document.getElementById("cookiesText").innerHTML ="<br /> <h1><big><i>Cookies</i></big></h1><br />" + 
" We will maintain certain data that you transmit to the Services for the purpose of managing the performance of the Services, as well as data relating to your use of the Services.<br /> <br />" +
" Although we perform regular routine backups of data, you are solely responsible for all data that you transmit or that relates to any activity you have undertaken using the Services.<br /> <br />" +
" You agree that we shall have no liability to you for any loss or corruption of any such data, and you hereby waive any right of action against us arising from any such loss or corruption of such data.<br /> <br />" +
" We are the owner or the licensee of all intellectual property rights in our Services, including all source code, databases, functionality, software, website designs, audio, video, text, photographs, and graphics in the Services.<br /> <br />" +
" Our Content and Marks are protected by copyright and trademark laws (and various other intellectual property rights and unfair competition laws) and treaties in the United States and around the world.<br /> <br />" +
" The Services may invite you to chat, contribute to, or participate in blogs, message boards, online forums, and other functionality during which you may create, submit, post, display, transmit, publish, distribute, or broadcast content and materials to us or through the Services, including but not limited to text, writings, video, audio, photographs, music, graphics, comments, reviews, rating suggestions, personal information, or other material Contributions. Any Submission that is publicly posted shall also be treated as a Contribution.<br /> <br />" +
" You may not access or use the Services for any purpose other than that for which we make the Services available.<br /> <br />" +
" The creation, distribution, transmission, public display, or performance, and the accessing, downloading, or copying of your Contributions do not and will not infringe the proprietary rights, including but not limited to the copyright, patent, trademark, trade secret, or moral rights of any third party.<br /> <br />" +
" Your Contributions are not used to harass or threaten (in the legal sense of those terms) any other person and to promote violence against a specific person or class of people.<br /> <br />" +
" Your Contributions do not include any offensive comments that are connected to race, national origin, gender, sexual preference, or physical handicap.<br /> <br />" +
" You agree that these Legal Terms will not be construed against us by virtue of having drafted them. <br /> <br />" +
" You hereby waive any and all defenses you may have based on the electronic form of these Legal Terms and the lack of signing by the parties hereto to execute these Legal Terms.<br />";